openapi: 3.0.0
info:
  title: ping
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /message/information:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
    post:
      summary: ''
      responses:
        '200':
          description: OK
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                libelle:
                  type: string
  /message/bulle:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                libelle:
                  type: string
    post:
      summary: ''
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                libelle:
                  type: string
components:
  schemas: {}
