openapi: 3.0.0
info:
  title: ping
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /message:
    post:
      summary: ''
      responses:
        '200':
          description: OK
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                wording:
                  type: string
                vision360:
                  type: boolean
                text:
                  type: string
                keywords:
                  type: array
                  items:
                    type: string
                start:
                  type: string
                  format: date
                end:
                  type: string
                  format: date
                entity:
                  type: array
                  items:
                    type: integer
                canals:
                  type: array
                  items:
                    type: string
                priority:
                  type: integer
                target:
                  type: object
                  properties:
                    federation:
                      type: boolean
                    agency:
                      type: string
                    clientList:
                      type: array
                      items:
                        type: string
                    targetType:
                      type: string
                      enum:
                        - federation
                        - agency
                        - clientList
                type:
                  type: string
                  enum:
                    - bulle
                    - information
                id:
                  type: integer
              required:
                - wording
                - vision360
                - text
                - start
                - entity
                - canals
            examples:
              example-1:
                value:
                  type: information
                  id: 1
                  wording: example-1
                  vision360: true
                  texte: "Message de type information d'exemple "
                  keywords:
                    - api
                    - esigelec
                    - ping
                  start: 8/11/2019
                  end: 8/12/2020
                  entity: '01'
                  canal: WEB
                  priority: 5
                  target:
                    targetType: federation
                    federation: true
                    agence: agence de rouen
                    listeClients:
                      id:
                        - 1
                        - 20
                        - 25
                        - 30
    parameters: []
    get:
      summary: ''
      operationId: get-message
      responses:
        '200':
          description: OK
      description: Get a list of message
  '/message/{id}':
    parameters:
      - type: string
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  wording:
                    type: string
                  vision360:
                    type: boolean
                  text:
                    type: string
                  keywords:
                    type: array
                    items:
                      type: string
                  start:
                    type: string
                    format: date
                  end:
                    type: string
                    format: date
                  entity:
                    type: array
                    items:
                      type: string
                  canals:
                    type: array
                    items:
                      type: string
                  priority:
                    type: integer
                  target:
                    type: object
                    properties:
                      federation:
                        type: boolean
                      agency:
                        type: string
                      clientList:
                        type: array
                        items:
                          type: string
                      targetType:
                        type: string
                        enum:
                          - federation
                          - agency
                          - clientType
                  type:
                    type: string
                    enum:
                      - information
                      - bulle
              examples:
                example-1:
                  value:
                    id: 123456abcdef
                    libelle: example-1
                    vision360: true
                    texte: "Messade de type information d'exemple pour l'update"
                    keyword:
                      - api
                      - esigelec
                      - ping
                    image:
                      - '? champ à compléteer pour le moment'
                    debut: 8/11/2019
                    fin: 8/12/2020
                    entite: '01'
                    canaux: WEB
                    priorite: 5
                    encart:
                      federation: true
                      agence: agence de rouen
                      listeClients:
                        id:
                          - 1
                          - 20
                          - 25
                          - 30
      description: Get message by id
    put:
      summary: ''
      responses:
        '201':
          description: Created
      description: Put with ID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                wording:
                  type: string
                vision360:
                  type: boolean
                text:
                  type: string
                keywords:
                  type: array
                  items:
                    type: string
                start:
                  type: string
                end:
                  type: string
                entity:
                  type: array
                  items:
                    type: integer
                canals:
                  type: array
                  items:
                    type: integer
                priority:
                  type: string
                target:
                  type: object
                  properties:
                    federation:
                      type: boolean
                    agency:
                      type: string
                    clientList:
                      type: array
                      items:
                        type: string
                    targetType:
                      type: string
                      enum:
                        - federation
                        - agency
                        - clientList
                id:
                  type: integer
                type:
                  type: string
                  enum:
                    - information
                    - bulle
            examples:
              example-1:
                value:
                  libelle: example-1
                  vision360: true
                  texte: "Messade de type information d'exemple pour l'update"
                  keyword:
                    - api
                    - esigelec
                    - ping
                  image:
                    - '? champ à compléteer pour le moment'
                  debut: 8/11/2019
                  fin: 8/12/2020
                  entite: '01'
                  canaux: WEB
                  priorite: 5
                  encart:
                    federation: true
                    agence: agence de rouen
                    listeClients:
                      id:
                        - 1
                        - 20
                        - 25
                        - 30
  '/message/{type}':
    parameters:
      - type: string
        name: type
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: 'OK '
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  type:
                    type: string
      operationId: 'get-message-{type}'
      description: Get message by type
      requestBody:
        description: ''
components:
  schemas: {}
